# Generated by Django 5.2.8 on 2025-11-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_contact_companycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='whatsapp_number',
            field=models.CharField(max_length=20),
        ),
    ]
