# Generated by Django 5.2.8 on 2025-11-30 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_companycontact_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontact',
            name='Email_Address',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
