# Generated by Django 5.2.8 on 2025-11-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_companycontact_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycontact',
            old_name='Email_Address',
            new_name='Email',
        ),
    ]
