# Generated by Django 5.2.8 on 2025-11-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_email_address_companycontact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycontact',
            old_name='Email',
            new_name='email',
        ),
    ]
