# Generated by Django 5.2.8 on 2025-11-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_email_companycontact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
                ('youtube', models.URLField()),
                ('reddit', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
    ]
