# Generated by Django 5.2.8 on 2026-01-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_socialhandle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('website_url', models.URLField(blank=True)),
                ('project_types', models.JSONField(blank=True, null=True)),
                ('budget', models.CharField(blank=True, choices=[('<10k', 'Less than 10,000'), ('25-50k', '25,000 - 50,000'), ('50-80k', '50,000 - 80,000'), ('80-130k', '80,000 - 1,30,000'), ('130k+', '1,30,000+'), ('deciding', 'Still deciding')], max_length=20)),
                ('timeline', models.CharField(blank=True, choices=[('asap', 'ASAP'), ('1-3', '1-3 months'), ('3-6', '3-6 months'), ('6+', '6+ months'), ('exploring', 'Just exploring')], max_length=20)),
                ('project_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
