# Generated by Django 5.2.8 on 2026-01-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_consultationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('service_type', models.CharField(choices=[('website-development', 'Website Development'), ('e-commerce-development', 'E-commerce Development'), ('custom-web-app', 'Custom Web App'), ('authentication-systems', 'Authentication Systems'), ('automation/bots', 'Automation / Bots'), ('crm-development', 'CRM Development'), ('mobile-app', 'Mobile App'), ('ai/ml-integration', 'AI / ML Integration'), ('api-development', 'API Development'), ('other', 'Other')], max_length=50)),
                ('project_requirements', models.TextField()),
                ('service_page', models.CharField(max_length=150)),
                ('source_city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='consultationform',
            name='ip_address',
        ),
    ]
