# Generated by Django 5.2.8 on 2026-01-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_webprojectinquiry_remove_consultationform_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('service_type', models.CharField(choices=[('automation', 'Automation Script'), ('scraping', 'Web Scraping Script'), ('api', 'API Integration Script'), ('data', 'Data Processing Script'), ('ai', 'AI / ML Script'), ('other', 'Other')], max_length=30)),
                ('project_requirements', models.TextField()),
                ('service_page', models.CharField(default='Python Automation Services Delhi', max_length=150)),
                ('source_city', models.CharField(default='Delhi', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
        ),
    ]
