# Generated by Django 5.2.8 on 2026-01-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pythonprojectinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('service_type', models.CharField(choices=[('chatbot', 'Chatbot Integration'), ('llm', 'LLM Integration'), ('automation', 'AI Automation'), ('search', 'Semantic Search / RAG'), ('document', 'Document AI'), ('custom', 'Custom / Advanced AI')], max_length=30)),
                ('project_requirements', models.TextField()),
                ('service_page', models.CharField(max_length=200)),
                ('source_city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
        ),
    ]
