# Generated by Django 5.2.8 on 2026-01-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_aiprojectinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAutomationInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('instagram_username', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(choices=[('automation', 'Automation Bot'), ('scheduling', 'Content Scheduling'), ('hashtags', 'Hashtag System'), ('analytics', 'Analytics Dashboard'), ('lead-gen', 'Lead Generation'), ('influencer', 'Influencer Tool')], max_length=30)),
                ('project_requirements', models.TextField()),
                ('service_page', models.CharField(max_length=200)),
                ('source_city', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instagram Automation Inquiry',
                'verbose_name_plural': 'Instagram Automation Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
