# Generated by Django 5.2.8 on 2026-01-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_instagramautomationinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAutomationInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_page_name', models.CharField(blank=True, max_length=150)),
                ('service_type', models.CharField(choices=[('messenger', 'Messenger Bot'), ('comment', 'Comment Automation'), ('lead', 'Lead Form Automation'), ('crm', 'CRM Integration'), ('ai', 'AI Messaging Funnel'), ('full', 'Full Automation Suite')], max_length=20)),
                ('project_requirements', models.TextField()),
                ('service_page', models.CharField(max_length=200)),
                ('source_city', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
