# Generated by Django 5.2.8 on 2026-01-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_facebookautomationinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAutomationInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('service_type', models.CharField(choices=[('custom', 'Custom WhatsApp Automation'), ('starter', 'Starter'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=20)),
                ('project_requirements', models.TextField()),
                ('service_page', models.CharField(max_length=255)),
                ('source_city', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
