# Generated by Django 5.2.8 on 2026-01-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_whatsappautomationinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyAutomationInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('service_type', models.CharField(choices=[('custom', 'Custom Tally Automation'), ('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='custom', max_length=20)),
                ('project_requirements', models.TextField()),
                ('service_page', models.CharField(max_length=200)),
                ('source_city', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='whatsappautomationinquiry',
            name='service_type',
            field=models.CharField(choices=[('custom', 'Custom WhatsApp Automation'), ('Starter', 'Starter'), ('Business', 'Business'), ('Enterprise', 'Enterprise')], max_length=20),
        ),
    ]
