# Generated by Django 5.2.8 on 2026-01-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_tallyautomationinquiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('interest', models.CharField(choices=[('web_development', 'Web Development'), ('python_scripts', 'Python Scripts'), ('ai_integration', 'AI Integration'), ('instagram_automation', 'Instagram Automation'), ('facebook_automation', 'Facebook Automation'), ('whatsapp_automation', 'WhatsApp Automation'), ('tally_automation', 'Tally Automation'), ('custom_software', 'Custom Software'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tallyautomationinquiry',
            name='service_type',
            field=models.CharField(choices=[('custom', 'Custom Tally Automation'), ('Basic', 'Basic'), ('Professional', 'Professional'), ('Enterprise', 'Enterprise')], default='custom', max_length=20),
        ),
    ]
